### ISSUE TITLE
Safari on MacOS Catalina 10.15.7 doesn't work

### ISSUE THREAD

**Issue by frituc** [haukex/de-en-dict#21]
It doesn't work on Safari on MacOS Catalina 10.15.7:

The dictionary failed to load! Please make sure you're using a modern browser and have a working Internet connection. Reload this page to try again. It is also possible that the dictionary server is offline - try [this link](https://ftp.tu-chemnitz.de/pub/Local/urz/ding/de-en-devel/) to check.

[Reported by a former Beolingus user]

**Comment by haukex** [comment]
Hi, thanks for the report. I did some research ([1](https://en.wikipedia.org/wiki/MacOS_version_history#Releases), [2](https://en.wikipedia.org/wiki/Safari_(web_browser)#Version_compatibility)) and apparently macOS 10.15 received its last update over two years ago, with five major releases since then. It seems the highest version of the Safari browser that works on that version of macOS is 15.6.1, but support also ended two years ago and there have also been two major releases since then.

Sorry, but since I'm working on this project in my free time, I unfortunately don't have the resources to support older versions of browsers, only the most recent versions - perhaps another developer reading this with access to an older macOS can suggest a fix. Or, if you are comfortable opening the [Safari developer tools](https://support.apple.com/en-us/guide/safari/sfri20948/13.0/mac/10.15) to take a look at the console and copy & pasting the error message here, perhaps that could give a hint as to whether there might be a trivial fix.

Similarly to [this thread on the Apple support forum](https://discussions.apple.com/thread/255230674), I have to recommend either upgrading your macOS, or installing a different browser that is up-to-date.
