### ISSUE TITLE
Button to show all results

### ISSUE THREAD

**Issue by frituc** [haukex/de-en-dict#24]
Beside the button [Show More] would it be possible to have a button [Show All] to show alle the matches?

**Comment by haukex** [comment]
It's theoretically possible to add a "Show All" button, but the issue is that for some searches that produce tens of thousands of results, rendering all of them at once would hang the browser, and potentially even crash it.

I've noticed that some shorter searches often produce around 250 results or so. I could offer two buttons: "Show 50 more" and "Show 200 more", how about that?

**Comment by haukex** [comment]
I've implemented this in cc94e588bb5b4fb43c83871c81b529e3ab55f471, please let me know if this is good or perhaps more is needed here.
