### ISSUE TITLE
table width responsive design (hyphenation?)

### ISSUE THREAD

**Issue by snieky42** [haukex/de-en-dict#28]
**Describe the bug**
sometime there is a problem with table width in small display f.e. if your looking for "Wohnung" on  mobile phone

**To Reproduce**
1. open the side on mobile phone
2. type "Wohnung" 
3.  See english result

**Expected behavior**
The results should also be shown in this display with without horizontal scrolling

**Screenshots**
![Bildschirmfoto vom 2024-08-21 14-44-39](https://github.com/user-attachments/assets/795098ff-8ae8-4add-8c2d-f87fad1155c0)

**Desktop (please complete the following information):**
 - OS: emulated phone (android, iOS)
 - Browser: firefox, chrome
 - Version current

**Comment by haukex** [comment]
Thanks for the feedback. Yes, this does happen - if you search for "Wohnung" and scroll down, you'll see why: the word "Wohnungseigentümergemeinschaften" is forcing the German side of the table to be that wide, and in this case the table scrolls horizontally (by design - you may notice that only the table scrolls, the rest of the page stays within the width of the browser).

This could be improved upon by adding hyphenation (e.g. putting [soft hyphens](https://en.wikipedia.org/wiki/Soft_hyphen) in the data), but this is unfortunately nontrivial, so I'll have to take some time to look at how to best implement it.

**Comment by frituc** [comment]
Should this be done in the translation database? E.g. by changing "Wohnungseigentümergemeinschaften" to "Woh·nungs·eigen·tümer·ge·mein·schaf·ten"?

**Comment by haukex** [comment]
That might be one possible solution, though changing the dictionary affects all code that is using it, including this app - the search would have to be adapted to handle the extra (hidden) characters in the data.

So doing the hyphenation only when rendering the dictionary feels a bit cleaner to me. I haven't yet had the time to see if there are JavaScript hyphenation libraries available.

Do you have hyphenation data for the dictionary available?

**Comment by haukex** [comment]
It turns out modern browsers support hyphenation natively, so I've simply turned on hyphenation on narrow screens.

**Comment by haukex** [comment]
Reopening because this isn't quite perfect yet: In Firefox it works fine, but in Chrome and Edge a search for "Wohnung" and then showing all results still causes the table to be wider than the screen. It seems like those two browsers aren't hyphenating "Wohnungsbaugenossenschaft" and "Wohnungsbaugenehmigungen", which Firefox is hyphenating.

**Comment by haukex** [comment]
After reconsidering this: Implementing our own hyphenation to work around this seems like overkill; if this is still bothering anyone, then this issue should be raised with Chrome and/or Edge and/or whatever hyphenation library they use.
